DROP database IF EXISTS ejercicio10;
CREATE DATABASE IF NOT EXISTS ejercicio10;
USE ejercicio10;
CREATE TABLE SALESMAN (
SALESMAN_ID NUMERIC(5) PRIMARY KEY auto_increment,
SALESMAN_NAME VARCHAR(50),
CITY VARCHAR (15),
COMMISION DECIMAL(5,2)
);
CREATE TABLE CUSTOMER (
CUSTOMER_ID NUMERIC (5) PRIMARY KEY auto_increment,
CITY VARCHAR(30),
GRADE NUMERIC (3)
);
CREATE TABLE ORDERS(
ORD_NO NUMERIC(5) PRIMARY KEY auto_increment,
PURCH_AMT DECIMAL(5,2),
ORD_DATE DATE,
CUSTOMER_ID NUMERIC(5),
SALESMAN_ID NUMERIC(5)
);
ALTER table ORDERS ADD CONSTRAINT CUSTOMER foreign key (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ORDERS ADD CONSTRAINT SALESMAN FOREIGN KEY (SALESMAN_ID) REFERENCES SALESMAN(SALESMAN_ID) ON DELETE CASCADE ON UPDATE CASCADE;


